name: Publisher(SNAPSHOTs)
on: [push]
jobs:
  build:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
        env:
          publishURL: "${{ secrets.PUBLISHURL }}"
          mavenName: "${{ secrets.MAVENNAME }}"
          mavenPassword: "${{ secrets.MAVENPASSWORD }}"
      - run: chmod +x ./gradlew

      - run: |
          ./gradlew publish